project:
  type: website
  output-dir: docs

website:
  title: "Neural Networks for Eddy Covariance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Presentation Slides
      - href: NN_for_EC.ipynb
        text: Example Code


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



